### ISSUE TITLE
Finding how to run scripts

### ISSUE THREAD

**Issue by GHNewbiee** [mrbenshef/Boop-GTK#232] opened 2021-02-12 19:35 UTC
What about adding "Click here or Press Ctrl+Shift+P to get started". It will be better for new users to know from the beginning, until they find it out, that "Press..." is not only a remark but it is also a button! *Tia*

**Comment by zoeyfyi** [comment] 2021-02-14 16:30
I would say that if its not obvious that its a button, that its a problem with the GTK theme you are using. I know some of them don't even put a border around buttons. The reason I am hesitant to add more text to the button is that it is already quite verbose.

**Comment by GHNewbiee** [comment] 2021-02-14 17:26
> I would say that if its not obvious that its a button,

Then, you agree that there is a small problem

> that its a problem with the GTK theme you are using.

I did not really know that about GTK theme. I suspect that cinnamon has the same problem.

> I know some of them don't even put a border around buttons.

That's true. There is not a border around buttons.

> The reason I am hesitant to add more text to the button is that it is already quite verbose.

Partly you are right; I do understand that, but on the other hand you will help the new users.

**Comment by zoeyfyi** [comment] 2021-02-14 18:52
I feel like this is more of an issue with cinnamon not making their buttons obviously intractable, which IMO is a big usability problem. 

Prehaps "Open command palette (Ctrl+Shift+P)" is better? Its actually describes what the button does, and is hopefully more obvious that its intractable.

**Comment by GHNewbiee** [comment] 2021-02-14 19:10
![Boop](https://user-images.githubusercontent.com/26875662/107886212-b9082780-6efe-11eb-9063-d245241c5847.png)

> I feel like this is more of an issue with cinnamon not making their buttons obviously intractable,

Maybe it is. I do not really know!

> which IMO is a big usability problem.

Yes, it is.

> Prehaps "Open command palette (Ctrl+Shift+P)" is better?

Again, hovering is required for someone to find out that it is a button.

> Its actually describes what the button does, and is hopefully more obvious that its intractable.

Can you add a (Script, Gear) icon left to text? Icons (maybe except logo icons) are almost always buttons. So, I hope new users will try to hover the icon to see what it is and does.

**Comment by ZanderBrown** [comment] 2021-02-15 10:26
_Zander wonders if @bertob might be able to have a quick looksy at this issue_

**Comment by bertob** [comment] 2021-02-15 10:32
Seems like a classic case of "this is why themes are a bad idea"? :D

https://blogs.gnome.org/tbernard/2018/10/15/restyling-apps-at-scale

**Comment by ZanderBrown** [comment] 2021-02-15 10:36
Hehe, yes - I'm kinda wondering about that button in general though

Perhaps the shortcut should be placeholder text on the source view or part of a first run? Feels a bit weird having a button labeled with its shortcut (esp when it grows the window width)

**Comment by GHNewbiee** [comment] 2021-02-15 11:13
IMHO, themes are not a bad idea at all. They give freedom to artists to express their creativity.

Immature "designers" without common sense of beauty and correct operation is the problem!

Anyway, I think that a beauty icon (gear, list, etc - see photo only as idea) placed correctly to the left of the "Open command palette (Ctrl+Shift+P)" text will help enough.

![boop1](https://user-images.githubusercontent.com/26875662/107939274-c963e500-6f86-11eb-8f7d-70689907fc24.png)

**Comment by zoeyfyi** [comment] 2021-02-15 12:42
[GNOME wiki](https://developer.gnome.org/Buttons/) suggests that its "more common to either have a label, or an icon, but not both". Also the docs for the method to [force buttons to show an icon and text](https://developer.gnome.org/gtk3/stable/GtkButton.html#gtk-button-set-always-show-image) says to "use this property if the button would be useless or hard to use without the image".

**Comment by GHNewbiee** [comment] 2021-02-15 13:14
I do not disagree with what GNOME suggests. But I also do not accept that it is a "bible" that I have to follow in blind!

At the end, just let it as it is. New users, having bad themes installed by default, will have some harder time until they find out that text is also a button, unless "Click or " text is added before "Press Ctrl+Shift+P to get started" text.

**Comment by bilelmoussaoui** [comment] 2021-02-15 13:40
> I do not disagree with what GNOME suggests. But I also do not accept that it is a "bible" that I have to follow in blind!
> 
> At the end, just let it as it is. New users, having bad themes installed by default, will have some harder time until they find out that text is also a button, unless "Click or " text is added before "Press Ctrl+Shift+P to get started" text.

From what you're saying, the issue to resolve is fixing those broken "themes".

**Comment by GHNewbiee** [comment] 2021-02-15 14:08
I have checked that, at least the theme I use, it adds borders to the buttons. See photo below.

![boop](https://user-images.githubusercontent.com/26875662/107956220-2370a480-6f9f-11eb-819f-193917d8ca4f.png)

In addition, all the apps I have opened randomly they display buttons with border.

@zoeyfyi Are you sure that you have not excluded the borders in some weird way?

**Comment by zoeyfyi** [comment] 2021-02-15 14:58
@GHNewbiee it seems to be intended behaviour in the cinnamon theme, look at `nemo` for example, none of the buttons in the header have borders.

![image](https://user-images.githubusercontent.com/2641780/107961709-2dde6e80-6f9e-11eb-9cbf-6df3b6b5b473.png)

**Comment by GHNewbiee** [comment] 2021-02-15 17:29
In the icons, `nemo` and other apps do not put border because icons are almost always buttons. Only in text buttons. See photos below:

![boop1](https://user-images.githubusercontent.com/26875662/107975399-570bf880-6fb8-11eb-8b0a-07e9ba9033aa.png)

![boop0](https://user-images.githubusercontent.com/26875662/107975262-25932d00-6fb8-11eb-81bd-e82b5e9a735f.png)

![boop2](https://user-images.githubusercontent.com/26875662/107975592-9cc8c100-6fb8-11eb-83a4-c8054e778c0f.png)

![boop3](https://user-images.githubusercontent.com/26875662/107975774-eb765b00-6fb8-11eb-984a-dafa3cd357d6.png)

In calculator above, the down arrow lies right of the text.

In addition, in Kazam and SimpleScreenRecorder, there are buttons with icon and text together.

Hence, IMHO,
- the problem is not caused by theme because icon buttons w/o border and text buttons with border are correctly displayed as per photos above.
- I think you are wrongly overlooking the fact that you use text as label rather as a button.
- You would also add an icon as Kazam and other apps do although GNOME guidelines do not suggest that.
- Are you sure that you have not excluded the borders by mistake?

**Comment by GHNewbiee** [comment] 2021-02-15 17:44
Are you sure that [`GtkButton`](https://developer.gnome.org/gtk3/stable/GtkButton.html) style properties ([`GtkStyleContext`](https://developer.gnome.org/gtk3/stable/GtkStyleContext.html#GtkBorder)) are set correctly?

**Comment by zoeyfyi** [comment] 2021-02-15 17:44
> In calculator above, the down arrow lies right of the text.

I am not sure what you mean, the button doesn't have a border. Take a look at the calendar app, the Today button doesn't have a border, and its text only.

![image](https://user-images.githubusercontent.com/2641780/107978653-1363bf80-6fb5-11eb-9810-4ca18ef9c163.png)

**Comment by GHNewbiee** [comment] 2021-02-15 17:54
Are you sure that [`GtkBorderStyle`](https://developer.gnome.org/gtk3/stable/GtkStyleContext.html#GtkBorderStyle) is not set to `GTK_BORDER_STYLE_NONE`?

**Comment by GHNewbiee** [comment] 2021-02-15 18:11
> I am not sure what you mean, the button doesn't have a border.

`Basic Mode` and down arrow are next to each other. When you click the arrow it opens.

> Take a look at the calendar app, the Today button doesn't have a border, and its text only.

I use the following calendar which none of the text is button.

![boop](https://user-images.githubusercontent.com/26875662/107980033-e1a42600-6fbf-11eb-91a2-b5c03e4b994d.png)

I do not know about the calendar of your picture.

Putting an icon iwo the text with border, like SimpleScreenRecorder does, makes the button obvious and get the attention. In your app it is like a label or hint than a button.

**Comment by ZanderBrown** [comment] 2021-02-15 18:17
> Are you sure that GtkBorderStyle is not set to GTK_BORDER_STYLE_NONE?

In your case it is set to NONE, because that is controlled by CSS and your theme did `border: none;`

**Comment by GHNewbiee** [comment] 2021-02-15 18:40
Then why, in all the other apps, all pure text buttons have a border? They may have explicitly set it through the app config/variables, isn't it possible? Does not the app developer have the possibility to overwrite/by-pass the default theme css values for a specific item?

**Comment by zoeyfyi** [comment] 2021-02-15 18:54
`border: none;` only applies to buttons in the header on your theme, other buttons receive a border. If I was to override the css for this app, it would "fix" it for your theme, but potentially break other themes. Ultimately, this is a stylistic choice made by the mint developers.

**Comment by GHNewbiee** [comment] 2021-02-15 19:33
> ... If I was to override the css for this app, it would "fix" it for your theme, but potentially break other themes.

Nobody wants that!

> Ultimately, this is a stylistic choice made by the mint developers.

Lately and ultimately, day by day, time has been getting closer to move to KDE Plasma.

**Comment by zoeyfyi** [comment] 2021-02-26 14:57
Closing, #235 resolved the actual issue here

**Closed as completed by zoeyfyi** 2021-02-26 14:57 UTC
